EXE = ifthenlooploop.dmadef

ifthenlooploop.ll: CFLAGS += -Os
#ifthenlooploop.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#ifthenlooploop.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: ifthenlooploop.dmadef.o
$(EXE).nomac: main.o
