EXE = triangle.dmadef

triangle.ll: CFLAGS += -Os
#triangle.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#triangle.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: triangle.dmadef.o
$(EXE).nomac: main.o
