EXE = loop.dmadef

loop.ll: CFLAGS += -Os
#loop.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#loop.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: loop.dmadef.o
$(EXE).nomac: main.o
