EXE = globaladd.dmadef

globaladd.ll: CFLAGS += -Os

#globaladd.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#globaladd.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globaladd.dmadef.o
$(EXE).nomac: main.o
