EXE = globaladd.nemdef

globaladd.ll: CFLAGS += -Os

#globaladd.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#globaladd.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globaladd.nemdef.o
$(EXE).nomac: main.o
