EXE = fork.dmadef

fork.ll: CFLAGS += -Os
#fork.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#fork.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: fork.dmadef.o
$(EXE).nomac: main.o
