EXE = globalmov2.nemdef

globalmov2.ll: CFLAGS += -Os

#globalmov2.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#globalmov2.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globalmov2.nemdef.o
$(EXE).nomac: main.o
