EXE = globalmov2.dmadef

globalmov2.ll: CFLAGS += -Os

#globalmov2.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#globalmov2.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globalmov2.dmadef.o
$(EXE).nomac: main.o
