EXE = ifthenloop.dmadef

ifthenloop.ll: CFLAGS += -Os
#ifthenloop.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#ifthenloop.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: ifthenloop.dmadef.o
$(EXE).nomac: main.o
