EXE = localvar.nemdef

localvar.ll: CFLAGS += -Os

#localvar.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#localvar.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: localvar.nemdef.o
$(EXE).nomac: main.o
