EXE = localvar.dmadef

localvar.ll: CFLAGS += -Os

#indirect.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#indirect.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: localvar.dmadef.o
$(EXE).nomac: main.o
