EXE = SPcheck2.dmadef

SPcheck2.ll: CFLAGS += -Os

#SPcheck2.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#SPcheck2.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: SPcheck2.dmadef.o
$(EXE).nomac: main.o
