EXE = SPcheck2.nemdef

SPcheck2.ll: CFLAGS += -Os

#SPcheck2.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#SPcheck2.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: SPcheck2.nemdef.o
$(EXE).nomac: main.o
