EXE = diamond.dmadef

diamond.ll: CFLAGS += -Os
#diamond.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: diamond.dmadef.o
$(EXE).nomac: main.o
