EXE = call.dmadef

call.ll: CFLAGS += -Os
#call.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#call.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: call.dmadef.o
$(EXE).nomac: main.o
