EXE = globalmov.nemdef

globalmov.ll: CFLAGS += -Os

#globalmov.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#globalmov.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globalmov.nemdef.o
$(EXE).nomac: main.o
