EXE = globalmov.dmadef

globalmov.ll: CFLAGS += -Os

#globalmov.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#globalmov.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: globalmov.dmadef.o
$(EXE).nomac: main.o
