EXE = pointglobal.nemdef

pointglobal.ll: CFLAGS += -Os

#pointglobal.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#pointglobal.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: pointglobal.nemdef.o
$(EXE).nomac: main.o
