EXE = pointglobal.dmadef

pointglobal.ll: CFLAGS += -Os

#pointglobal.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#pointglobal.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: pointglobal.dmadef.o
$(EXE).nomac: main.o
