EXE = bsl.dmadef

bsl.ll: CFLAGS += -Os
#bsl.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: bsl.dmadef.o
$(EXE).nomac: main.o
