EXE = SPcheck1.dmadef

SPcheck1.ll: CFLAGS += -Os

#SPcheck1.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#SPcheck1.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: SPcheck1.dmadef.o
$(EXE).nomac: main.o
