EXE = SPcheck1.nemdef

SPcheck1.ll: CFLAGS += -Os

#SPcheck1.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#SPcheck1.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: SPcheck1.nemdef.o
$(EXE).nomac: main.o
