EXE = mulhi3.dmadef

mulhi3.ll: CFLAGS += -Os
#mulhi3.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#mulhi3.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: mulhi3.dmadef.o
$(EXE).nomac: main.o
