EXE = multifork.dmadef

multifork.ll: CFLAGS += -Os
#multifork.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#multifork.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: multifork.dmadef.o
$(EXE).nomac: main.o
