EXE = modexp.dmadef

modexp.ll: CFLAGS += -Os
#modexp.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#modexp.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: modexp.dmadef.o
$(EXE).nomac: main.o
