EXE = ifcompound.dmadef

ifcompound.ll: CFLAGS += -Os
#ifcompound.dmadef.s: LLCFLAGSDMADEF += -debug-only=msp430-dma-defender
#ifcompound.dmadef.s: LLCFLAGSDMADEF += -msp430-dma-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: ifcompound.dmadef.o
$(EXE).nomac: main.o
